### ISSUE TITLE
If SME deletes a product, the User still have "latest" key

### ISSUE THREAD

**Issue by shukkkur** [Curiouspaul1/telegram-business#3]
Thank you very much for all the work you did! 
Me and my fellow students are using it, so thanks man!
![image](https://user-images.githubusercontent.com/78250180/163224572-dcef27a5-7af0-4691-9446-ebdb3eebadde.png)
Anyway, when SME decides to delete a product from catalogue
https://github.com/Curiouspaul1/telegram-business/blob/8ca9209f9f174c6ee9db97250c9487a48fbf3b8c/handlers.py#L521-L528
Our User instance in database still have `"latest"` key within the `data` dictionary. As a result, the following lines
https://github.com/Curiouspaul1/telegram-business/blob/8ca9209f9f174c6ee9db97250c9487a48fbf3b8c/handlers.py#L675-L682
result in error which fetches the except block and prevents us from selecting the previous businesses
I tried to remove the "latest" key after the user deletes a product, however I couldn't achieve that since I can't seem to grasp the FaunaDB syntax. 
Also, the thumbnail also remains in cloudinary
Hope for your help!

**Comment by Curiouspaul1** [comment]
I believe this is the same issue as the first so I'll close this as i have pushed an update to fix that
