### ISSUE TITLE
MAJOR BUG - Please Help 

### ISSUE THREAD

**Issue by shukkkur** [Curiouspaul1/telegram-business#4]
I stumbled upon a bug which doesn't display SME after he deletes a product! 

So, assuming SME has two products published and inside **Business** in database his `latest` key refers to last product. However, here: 
https://github.com/Curiouspaul1/telegram-business/blob/8ca9209f9f174c6ee9db97250c9487a48fbf3b8c/handlers.py#L521-L525
after removing the product, we are not updated the `latest` key and it now refers to deleted product. As a result, 
https://github.com/Curiouspaul1/telegram-business/blob/8ca9209f9f174c6ee9db97250c9487a48fbf3b8c/handlers.py#L675-L682
trying to fetch a thumbnail image results in error and User doesn't get to show up at all. 

I can't think of a solution. Please help, cause manually updating the database isn't the best option and it's affecting the overall functionality of the bot.

Hope on your help, Paul!

**Comment by Curiouspaul1** [comment]
ah yes i see what you mean. Thanks for reporting this, will fix this ASAP

**Comment by Curiouspaul1** [comment]
I should also mention that I am making some minor structural changes to make the code more readable

**Comment by Curiouspaul1** [comment]
hey i just pushed a fix for this issue check this commit 763a882b12333710499ea1a2b07de86f5d0c0a26

**Comment by shukkkur** [comment]
Thanks a lot!)
